CREATE TABLE IF NOT EXISTS account_user (
                                ID BIGSERIAL PRIMARY KEY,
                                username varchar(255) NOT NULL UNIQUE,
                                password varchar(255) NOT NULL,
                                firstname varchar(255) NOT NULL,
                                lastname varchar(255) NOT NULL,
                                janitor_id bigint DEFAULT NULL,
                                account_non_expired boolean NOT NULL,
                                account_non_locked boolean NOT NULL,
                                credentials_non_expired boolean NOT NULL,
                                enabled boolean NOT NULL,
                                email varchar(100) DEFAULT NULL,
                                phone varchar(30) NOT NULL,
                                STATUS varchar(30) DEFAULT NULL,
                                VERSION int NOT NULL DEFAULT '0',
                                CREATED_BY varchar(255) DEFAULT NULL,
                                CREATED_DATE timestamp NULL DEFAULT NULL,
                                LAST_MODIFIED_BY varchar(255) DEFAULT NULL,
                                LAST_MODIFIED_DATE timestamp NULL DEFAULT NULL
);
